//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::ApplicationData.Implementation.ApplicationDataObjectContext>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService()
        {
            return new global::LightSwitchApplication.DataWorkspace().ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::ApplicationData.Implementation.ApplicationDataObjectContext>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Program> Programs_All()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Program> query;
            query = this.GetQuery<global::ApplicationData.Implementation.Program>("Programs");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Instructor> Instructors_All()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Instructor> query;
            query = this.GetQuery<global::ApplicationData.Implementation.Instructor>("Instructors");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Section> Sections_All()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Section> query;
            query = this.GetQuery<global::ApplicationData.Implementation.Section>("Sections");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Client> Clients_All()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Client> query;
            query = this.GetQuery<global::ApplicationData.Implementation.Client>("Clients");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Section> AvailableSections(global::System.Nullable<int> ClientId)
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Section> query;
            query = this.GetQuery<global::ApplicationData.Implementation.Section>("Sections");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Section> SectionsByProgram(global::System.Nullable<int> CategoryId)
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Section> query;
            query = this.GetQuery<global::ApplicationData.Implementation.Section>("Sections");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Sponsor> Sponsors_All()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Sponsor> query;
            query = this.GetQuery<global::ApplicationData.Implementation.Sponsor>("Sponsors");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Section> FilterSections(string FilterTerm)
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Section> query;
            query = this.GetQuery<global::ApplicationData.Implementation.Section>("Sections");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Section> SectionsByClient(global::System.Nullable<int> ClientId)
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Section> query;
            query = this.GetQuery<global::ApplicationData.Implementation.Section>("Sections");
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::ApplicationData.Implementation.Program))
            {
                return new global::ApplicationData.Implementation.Program();
            }
            if (type == typeof(global::ApplicationData.Implementation.Course))
            {
                return new global::ApplicationData.Implementation.Course();
            }
            if (type == typeof(global::ApplicationData.Implementation.Instructor))
            {
                return new global::ApplicationData.Implementation.Instructor();
            }
            if (type == typeof(global::ApplicationData.Implementation.Section))
            {
                return new global::ApplicationData.Implementation.Section();
            }
            if (type == typeof(global::ApplicationData.Implementation.Enrollment))
            {
                return new global::ApplicationData.Implementation.Enrollment();
            }
            if (type == typeof(global::ApplicationData.Implementation.Client))
            {
                return new global::ApplicationData.Implementation.Client();
            }
            if (type == typeof(global::ApplicationData.Implementation.CourseProgram))
            {
                return new global::ApplicationData.Implementation.CourseProgram();
            }
            if (type == typeof(global::ApplicationData.Implementation.Sponsorship))
            {
                return new global::ApplicationData.Implementation.Sponsorship();
            }
            if (type == typeof(global::ApplicationData.Implementation.Sponsor))
            {
                return new global::ApplicationData.Implementation.Sponsor();
            }
            if (type == typeof(global::ApplicationData.Implementation.SponsorRelationship))
            {
                return new global::ApplicationData.Implementation.SponsorRelationship();
            }
            if (type == typeof(global::ApplicationData.Implementation.ScheduleViewAppt))
            {
                return new global::ApplicationData.Implementation.ScheduleViewAppt();
            }
            if (type == typeof(global::ApplicationData.Implementation.Table1Item))
            {
                return new global::ApplicationData.Implementation.Table1Item();
            }
            if (type == typeof(global::ApplicationData.Implementation.Pool))
            {
                return new global::ApplicationData.Implementation.Pool();
            }
            if (type == typeof(global::ApplicationData.Implementation.Attendance))
            {
                return new global::ApplicationData.Implementation.Attendance();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::ApplicationData.Implementation.ApplicationDataObjectContext CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::ApplicationData.Implementation.ApplicationDataObjectContext(base.GetEntityConnectionString(
                "_IntrinsicData", 
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl", 
                "System.Data.SqlClient"));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Program))
            {
                return new global::ApplicationData.Implementation.Program();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Course))
            {
                return new global::ApplicationData.Implementation.Course();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Instructor))
            {
                return new global::ApplicationData.Implementation.Instructor();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Section))
            {
                return new global::ApplicationData.Implementation.Section();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Enrollment))
            {
                return new global::ApplicationData.Implementation.Enrollment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Client))
            {
                return new global::ApplicationData.Implementation.Client();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CourseProgram))
            {
                return new global::ApplicationData.Implementation.CourseProgram();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Sponsorship))
            {
                return new global::ApplicationData.Implementation.Sponsorship();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Sponsor))
            {
                return new global::ApplicationData.Implementation.Sponsor();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SponsorRelationship))
            {
                return new global::ApplicationData.Implementation.SponsorRelationship();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ScheduleViewAppt))
            {
                return new global::ApplicationData.Implementation.ScheduleViewAppt();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Table1Item))
            {
                return new global::ApplicationData.Implementation.Table1Item();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Pool))
            {
                return new global::ApplicationData.Implementation.Pool();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Attendance))
            {
                return new global::ApplicationData.Implementation.Attendance();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Program) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Program);
            }
            if (typeof(global::LightSwitchApplication.Course) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Course);
            }
            if (typeof(global::LightSwitchApplication.Instructor) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Instructor);
            }
            if (typeof(global::LightSwitchApplication.Section) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Section);
            }
            if (typeof(global::LightSwitchApplication.Enrollment) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Enrollment);
            }
            if (typeof(global::LightSwitchApplication.Client) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Client);
            }
            if (typeof(global::LightSwitchApplication.CourseProgram) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.CourseProgram);
            }
            if (typeof(global::LightSwitchApplication.Sponsorship) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Sponsorship);
            }
            if (typeof(global::LightSwitchApplication.Sponsor) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Sponsor);
            }
            if (typeof(global::LightSwitchApplication.SponsorRelationship) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.SponsorRelationship);
            }
            if (typeof(global::LightSwitchApplication.ScheduleViewAppt) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.ScheduleViewAppt);
            }
            if (typeof(global::LightSwitchApplication.Table1Item) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Table1Item);
            }
            if (typeof(global::LightSwitchApplication.Pool) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Pool);
            }
            if (typeof(global::LightSwitchApplication.Attendance) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Attendance);
            }
            return null;
        }
    }
}

namespace ApplicationData.Implementation
{

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Program :
        global::LightSwitchApplication.Program.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Program.DetailsClass.IImplementation.CourseProgramItem
        {
            get
            {
                return this.CourseProgramItem;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Course :
        global::LightSwitchApplication.Course.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.Sections
        {
            get
            {
                return this.Sections;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.CourseProgram
        {
            get
            {
                return this.CourseProgram;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Instructor :
        global::LightSwitchApplication.Instructor.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Instructor.DetailsClass.IImplementation.Sections
        {
            get
            {
                return this.Sections;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Section :
        global::LightSwitchApplication.Section.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Section.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::ApplicationData.Implementation.Course)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Course");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Section.DetailsClass.IImplementation.Instructor
        {
            get
            {
                return this.Instructor;
            }
            set
            {
                this.Instructor = (global::ApplicationData.Implementation.Instructor)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Instructor");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Section.DetailsClass.IImplementation.Enrollments
        {
            get
            {
                return this.Enrollments;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Section.DetailsClass.IImplementation.Attendance
        {
            get
            {
                return this.Attendance;
            }
        }
        
        partial void OnSection_CourseChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Course");
            }
        }
        
        partial void OnSection_InstructorChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Instructor");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Enrollment :
        global::LightSwitchApplication.Enrollment.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Enrollment.DetailsClass.IImplementation.Section
        {
            get
            {
                return this.Section;
            }
            set
            {
                this.Section = (global::ApplicationData.Implementation.Section)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Section");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Enrollment.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::ApplicationData.Implementation.Client)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Client");
                }
            }
        }
        
        partial void OnEnrollment_SectionChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Section");
            }
        }
        
        partial void OnEnrollment_StudentChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Client");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Client :
        global::LightSwitchApplication.Client.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.Enrollments
        {
            get
            {
                return this.Enrollments;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.Sponsorships
        {
            get
            {
                return this.Sponsorships;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.SponsorRelationship
        {
            get
            {
                return this.SponsorRelationship;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.Attendances
        {
            get
            {
                return this.Attendances;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CourseProgram :
        global::LightSwitchApplication.CourseProgram.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CourseProgram.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::ApplicationData.Implementation.Course)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Course");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CourseProgram.DetailsClass.IImplementation.Program
        {
            get
            {
                return this.Program;
            }
            set
            {
                this.Program = (global::ApplicationData.Implementation.Program)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Program");
                }
            }
        }
        
        partial void OnCourseCategory_CourseChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Course");
            }
        }
        
        partial void OnCourseCategory_CategoryChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Program");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Sponsorship :
        global::LightSwitchApplication.Sponsorship.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Sponsorship.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::ApplicationData.Implementation.Client)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Client");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Sponsorship.DetailsClass.IImplementation.Sponsor
        {
            get
            {
                return this.Sponsor;
            }
            set
            {
                this.Sponsor = (global::ApplicationData.Implementation.Sponsor)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Sponsor");
                }
            }
        }
        
        partial void OnClient_SponsorshipChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Client");
            }
        }
        
        partial void OnSponsor_SponsorshipChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Sponsor");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Sponsor :
        global::LightSwitchApplication.Sponsor.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Sponsor.DetailsClass.IImplementation.SponsorRelationship
        {
            get
            {
                return this.SponsorRelationship;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Sponsor.DetailsClass.IImplementation.Sponsorships
        {
            get
            {
                return this.Sponsorships;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SponsorRelationship :
        global::LightSwitchApplication.SponsorRelationship.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.SponsorRelationship.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::ApplicationData.Implementation.Client)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Client");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.SponsorRelationship.DetailsClass.IImplementation.Sponsor
        {
            get
            {
                return this.Sponsor;
            }
            set
            {
                this.Sponsor = (global::ApplicationData.Implementation.Sponsor)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Sponsor");
                }
            }
        }
        
        partial void OnClient_RelationshipTypeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Client");
            }
        }
        
        partial void OnSponsor_RelationshipTypeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Sponsor");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ScheduleViewAppt :
        global::LightSwitchApplication.ScheduleViewAppt.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Table1Item :
        global::LightSwitchApplication.Table1Item.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Pool :
        global::LightSwitchApplication.Pool.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Attendance :
        global::LightSwitchApplication.Attendance.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Attendance.DetailsClass.IImplementation.Section
        {
            get
            {
                return this.Section;
            }
            set
            {
                this.Section = (global::ApplicationData.Implementation.Section)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Section");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Attendance.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::ApplicationData.Implementation.Client)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Client");
                }
            }
        }
        
        partial void OnActivity_SectionChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Section");
            }
        }
        
        partial void OnAttendance_ClientChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Client");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

