

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class SponsorRelationship : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the SponsorRelationship entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SponsorRelationship()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SponsorRelationship(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SponsorRelationship> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.SponsorRelationship.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SponsorRelationship_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SponsorRelationship_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.SponsorRelationship.DetailsClass.GetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.SponsorRelationship.DetailsClass.SetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.SponsorRelationship.DetailsClass.GetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.SponsorRelationship.DetailsClass.SetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Relationship
        {
            get
            {
                return global::LightSwitchApplication.SponsorRelationship.DetailsClass.GetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Relationship);
            }
            set
            {
                global::LightSwitchApplication.SponsorRelationship.DetailsClass.SetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Relationship, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Relationship_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Relationship_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Relationship_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsPrimary
        {
            get
            {
                return global::LightSwitchApplication.SponsorRelationship.DetailsClass.GetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.IsPrimary);
            }
            set
            {
                global::LightSwitchApplication.SponsorRelationship.DetailsClass.SetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.IsPrimary, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsPrimary_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsPrimary_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsPrimary_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Client Client
        {
            get
            {
                return global::LightSwitchApplication.SponsorRelationship.DetailsClass.GetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Client);
            }
            set
            {
                global::LightSwitchApplication.SponsorRelationship.DetailsClass.SetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Client, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Sponsor Sponsor
        {
            get
            {
                return global::LightSwitchApplication.SponsorRelationship.DetailsClass.GetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Sponsor);
            }
            set
            {
                global::LightSwitchApplication.SponsorRelationship.DetailsClass.SetValue(this, global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Sponsor, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sponsor_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sponsor_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sponsor_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.SponsorRelationship,
                global::LightSwitchApplication.SponsorRelationship.DetailsClass,
                global::LightSwitchApplication.SponsorRelationship.DetailsClass.IImplementation,
                global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass>.Entry
                __SponsorRelationshipEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass>.Entry(
                    global::LightSwitchApplication.SponsorRelationship.DetailsClass.__SponsorRelationship_CreateNew,
                    global::LightSwitchApplication.SponsorRelationship.DetailsClass.__SponsorRelationship_Created,
                    global::LightSwitchApplication.SponsorRelationship.DetailsClass.__SponsorRelationship_AllowSaveWithErrors);
            private static global::LightSwitchApplication.SponsorRelationship __SponsorRelationship_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SponsorRelationship> es)
            {
                return new global::LightSwitchApplication.SponsorRelationship(es);
            }
            private static void __SponsorRelationship_Created(global::LightSwitchApplication.SponsorRelationship e)
            {
                e.SponsorRelationship_Created();
            }
            private static bool __SponsorRelationship_AllowSaveWithErrors(global::LightSwitchApplication.SponsorRelationship e)
            {
                bool result = false;
                e.SponsorRelationship_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, string> Relationship
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Relationship) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, bool> IsPrimary
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.IsPrimary) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Client> Client
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Client) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Client>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Sponsor> Sponsor
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Sponsor) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Sponsor>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Relationship { get; set; }
                new bool IsPrimary { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Client { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Sponsor { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, int>.Data> c, global::LightSwitchApplication.SponsorRelationship.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.SponsorRelationship e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.SponsorRelationship e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.SponsorRelationship e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.SponsorRelationship.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.SponsorRelationship e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.SponsorRelationship e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.SponsorRelationship e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, string>.Entry
                    Relationship = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, string>.Entry(
                        "Relationship",
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Relationship_Stub,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Relationship_ComputeIsReadOnly,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Relationship_Validate,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Relationship_GetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Relationship_SetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Relationship_OnValueChanged);
                private static void _Relationship_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, string>.Data> c, global::LightSwitchApplication.SponsorRelationship.DetailsClass d, object sf)
                {
                    c(d, ref d._Relationship, sf);
                }
                private static bool _Relationship_ComputeIsReadOnly(global::LightSwitchApplication.SponsorRelationship e)
                {
                    bool result = false;
                    e.Relationship_IsReadOnly(ref result);
                    return result;
                }
                private static void _Relationship_Validate(global::LightSwitchApplication.SponsorRelationship e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Relationship_Validate(r);
                }
                private static string _Relationship_GetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d)
                {
                    return d.ImplementationEntity.Relationship;
                }
                private static void _Relationship_SetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Relationship = v;
                }
                private static void _Relationship_OnValueChanged(global::LightSwitchApplication.SponsorRelationship e)
                {
                    e.Relationship_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, bool>.Entry
                    IsPrimary = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, bool>.Entry(
                        "IsPrimary",
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._IsPrimary_Stub,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._IsPrimary_ComputeIsReadOnly,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._IsPrimary_Validate,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._IsPrimary_GetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._IsPrimary_SetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._IsPrimary_OnValueChanged);
                private static void _IsPrimary_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, bool>.Data> c, global::LightSwitchApplication.SponsorRelationship.DetailsClass d, object sf)
                {
                    c(d, ref d._IsPrimary, sf);
                }
                private static bool _IsPrimary_ComputeIsReadOnly(global::LightSwitchApplication.SponsorRelationship e)
                {
                    bool result = false;
                    e.IsPrimary_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsPrimary_Validate(global::LightSwitchApplication.SponsorRelationship e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsPrimary_Validate(r);
                }
                private static bool _IsPrimary_GetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d)
                {
                    return d.ImplementationEntity.IsPrimary;
                }
                private static void _IsPrimary_SetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.IsPrimary = v;
                }
                private static void _IsPrimary_OnValueChanged(global::LightSwitchApplication.SponsorRelationship e)
                {
                    e.IsPrimary_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Client>.Entry
                    Client = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Client>.Entry(
                        "Client",
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Client_Stub,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Client_ComputeIsReadOnly,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Client_Validate,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Client_GetCoreImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Client_GetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Client_SetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Client_Refresh,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Client_OnValueChanged);
                private static void _Client_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Client>.Data> c, global::LightSwitchApplication.SponsorRelationship.DetailsClass d, object sf)
                {
                    c(d, ref d._Client, sf);
                }
                private static bool _Client_ComputeIsReadOnly(global::LightSwitchApplication.SponsorRelationship e)
                {
                    bool result = false;
                    e.Client_IsReadOnly(ref result);
                    return result;
                }
                private static void _Client_Validate(global::LightSwitchApplication.SponsorRelationship e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Client_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Client_GetCoreImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d)
                {
                    return d.ImplementationEntity.Client;
                }
                private static global::LightSwitchApplication.Client _Client_GetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Client, ref d._Client);
                }
                private static void _Client_SetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d, global::LightSwitchApplication.Client v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Client, ref d._Client, (i, ev) => i.Client = ev, v);
                }
                private static void _Client_Refresh(global::LightSwitchApplication.SponsorRelationship.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Client, ref d._Client);
                }
                private static void _Client_OnValueChanged(global::LightSwitchApplication.SponsorRelationship e)
                {
                    e.Client_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Sponsor>.Entry
                    Sponsor = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Sponsor>.Entry(
                        "Sponsor",
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Sponsor_Stub,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Sponsor_ComputeIsReadOnly,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Sponsor_Validate,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Sponsor_GetCoreImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Sponsor_GetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Sponsor_SetImplementationValue,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Sponsor_Refresh,
                        global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties._Sponsor_OnValueChanged);
                private static void _Sponsor_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Sponsor>.Data> c, global::LightSwitchApplication.SponsorRelationship.DetailsClass d, object sf)
                {
                    c(d, ref d._Sponsor, sf);
                }
                private static bool _Sponsor_ComputeIsReadOnly(global::LightSwitchApplication.SponsorRelationship e)
                {
                    bool result = false;
                    e.Sponsor_IsReadOnly(ref result);
                    return result;
                }
                private static void _Sponsor_Validate(global::LightSwitchApplication.SponsorRelationship e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Sponsor_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Sponsor_GetCoreImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d)
                {
                    return d.ImplementationEntity.Sponsor;
                }
                private static global::LightSwitchApplication.Sponsor _Sponsor_GetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Sponsor, global::LightSwitchApplication.Sponsor.DetailsClass>(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Sponsor, ref d._Sponsor);
                }
                private static void _Sponsor_SetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass d, global::LightSwitchApplication.Sponsor v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Sponsor, ref d._Sponsor, (i, ev) => i.Sponsor = ev, v);
                }
                private static void _Sponsor_Refresh(global::LightSwitchApplication.SponsorRelationship.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.SponsorRelationship.DetailsClass.PropertySetProperties.Sponsor, ref d._Sponsor);
                }
                private static void _Sponsor_OnValueChanged(global::LightSwitchApplication.SponsorRelationship e)
                {
                    e.Sponsor_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, string>.Data _Relationship;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, bool>.Data _IsPrimary;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Client>.Data _Client;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SponsorRelationship, global::LightSwitchApplication.SponsorRelationship.DetailsClass, global::LightSwitchApplication.Sponsor>.Data _Sponsor;
            
        }
    
        #endregion
    }
    
    #endregion
}
