

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Course : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Course entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Course()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Course(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Course> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Course.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TeachingRatio
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.TeachingRatio);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.TeachingRatio, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeachingRatio_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeachingRatio_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TeachingRatio_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PoolArea
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.PoolArea);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.PoolArea, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PoolArea_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PoolArea_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PoolArea_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> ClassSize
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.ClassSize);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.ClassSize, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClassSize_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClassSize_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClassSize_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Section> Sections
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Sections);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Section> SectionsQuery
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetQuery(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Sections);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.CourseProgram> CourseProgram
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseProgram);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CourseProgram> CourseProgramQuery
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetQuery(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseProgram);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Course,
                global::LightSwitchApplication.Course.DetailsClass,
                global::LightSwitchApplication.Course.DetailsClass.IImplementation,
                global::LightSwitchApplication.Course.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>.Entry
                __CourseEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>.Entry(
                    global::LightSwitchApplication.Course.DetailsClass.__Course_CreateNew,
                    global::LightSwitchApplication.Course.DetailsClass.__Course_Created,
                    global::LightSwitchApplication.Course.DetailsClass.__Course_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Course __Course_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Course> es)
            {
                return new global::LightSwitchApplication.Course(es);
            }
            private static void __Course_Created(global::LightSwitchApplication.Course e)
            {
                e.Course_Created();
            }
            private static bool __Course_AllowSaveWithErrors(global::LightSwitchApplication.Course e)
            {
                bool result = false;
                e.Course_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Course.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string> TeachingRatio
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.TeachingRatio) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string> PoolArea
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.PoolArea) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>> ClassSize
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.ClassSize) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Section> Sections
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Sections) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Section>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseProgram> CourseProgram
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseProgram) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseProgram>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Title { get; set; }
                new string Description { get; set; }
                new byte[] RowVersion { get; set; }
                new string TeachingRatio { get; set; }
                new string PoolArea { get; set; }
                new global::System.Nullable<int> ClassSize { get; set; }
                new global::System.Collections.IEnumerable Sections { get; }
                new global::System.Collections.IEnumerable CourseProgram { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry
                    TeachingRatio = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry(
                        "TeachingRatio",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._TeachingRatio_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._TeachingRatio_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._TeachingRatio_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._TeachingRatio_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._TeachingRatio_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._TeachingRatio_OnValueChanged);
                private static void _TeachingRatio_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._TeachingRatio, sf);
                }
                private static bool _TeachingRatio_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.TeachingRatio_IsReadOnly(ref result);
                    return result;
                }
                private static void _TeachingRatio_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TeachingRatio_Validate(r);
                }
                private static string _TeachingRatio_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.TeachingRatio;
                }
                private static void _TeachingRatio_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, string v)
                {
                    d.ImplementationEntity.TeachingRatio = v;
                }
                private static void _TeachingRatio_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.TeachingRatio_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry
                    PoolArea = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry(
                        "PoolArea",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._PoolArea_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._PoolArea_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._PoolArea_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._PoolArea_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._PoolArea_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._PoolArea_OnValueChanged);
                private static void _PoolArea_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._PoolArea, sf);
                }
                private static bool _PoolArea_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.PoolArea_IsReadOnly(ref result);
                    return result;
                }
                private static void _PoolArea_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PoolArea_Validate(r);
                }
                private static string _PoolArea_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.PoolArea;
                }
                private static void _PoolArea_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PoolArea = v;
                }
                private static void _PoolArea_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.PoolArea_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Entry
                    ClassSize = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Entry(
                        "ClassSize",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ClassSize_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ClassSize_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ClassSize_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ClassSize_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ClassSize_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ClassSize_OnValueChanged);
                private static void _ClassSize_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._ClassSize, sf);
                }
                private static bool _ClassSize_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.ClassSize_IsReadOnly(ref result);
                    return result;
                }
                private static void _ClassSize_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ClassSize_Validate(r);
                }
                private static global::System.Nullable<int> _ClassSize_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.ClassSize;
                }
                private static void _ClassSize_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.ClassSize = v;
                }
                private static void _ClassSize_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.ClassSize_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Section>.Entry
                    Sections = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Section>.Entry(
                        "Sections",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Sections_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Sections_GetReferencedEntities,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Sections_GetEntityCollection);
                private static void _Sections_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Section>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._Sections, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Section> _Sections_GetReferencedEntities(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Section, global::LightSwitchApplication.Section.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Sections, ref d._Sections);
                }
                private static global::System.Collections.IEnumerable _Sections_GetEntityCollection(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.Sections;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseProgram>.Entry
                    CourseProgram = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseProgram>.Entry(
                        "CourseProgram",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseProgram_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseProgram_GetReferencedEntities,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseProgram_GetEntityCollection);
                private static void _CourseProgram_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseProgram>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseProgram, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.CourseProgram> _CourseProgram_GetReferencedEntities(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.CourseProgram, global::LightSwitchApplication.CourseProgram.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseProgram, ref d._CourseProgram);
                }
                private static global::System.Collections.IEnumerable _CourseProgram_GetEntityCollection(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseProgram;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data _TeachingRatio;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data _PoolArea;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Data _ClassSize;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.Section>.Data _Sections;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseProgram>.Data _CourseProgram;
            
        }
    
        #endregion
    }
    
    #endregion
}
